INSERT INTO vendors(vendor_name, city_name, adress)
VALUES
('Dispatch', 'Little Italy', '267 Rue Saint-Zotique Ouest'),
('Cafe Pista', 'Rosemont', '500 Beaubien'),
('Cafe Dei Campi', 'Rosemont', '1360 Boulevard Rosemont'),
('Cafe L/Etincelle', 'Rosemont', '1991 Rue Beaubien E'),
('Le Bruloir', 'Ahuntsic', '318 Fleury'),
('Le Cafe Creme', 'Ahuntsic', '1505 Rue Fleury E'),
('Cafe Aroma Paninoteca', 'Fleury', '1520 Rue Fleury'),
('Cafe Vito', 'Villeray', '151 Villeray'),
('Melk', 'NDG', '5612 Monkland'),
('Cafe Larue & Fils', 'Villeray', '244 de Castelnau'),
('Cafe Myriade', 'Little Italy', '1432 Mackay St'),
('Pikolo Espresso Bar', 'Little Italy', '3418b Park Ave'),
('Ferlucci', 'Villeray', '432 de Castelnau'),
('Cafe Olimpico', 'Little Italy', '267 Rue Saint-Zotique Ouest'),
('Cafe Olimpico', 'Little Italy', '267 Rue Saint-Zotique Ouest'),
('Cafe Parvis', 'Little Italy', '433 Mayor St'),
('Tommy', 'Fleury', '1432 Mackay St'),
('Picolo Espresso Bar', 'Villeray', '3418b Park Ave'),
('Café Névé', 'Rosemont', '151 Rue Rachel E'),
('Cafe Olimpico', 'Little Italy', '267 Rue Saint-Zotique Ouest'),
('Paquebot', 'Rosemont', '2110 Belanger'),
('Cafe Odessa', 'Rosemont', '65 Beaubien'),
('La Brume Dans Mes Lunettes', 'Rosemont', '378 Saint-Zotique'),
('Caffe San Simeon', 'Little Italy', '39 Dante'),
('Caffe Italia', 'Little Italy', '6840 Saint-Laurent'),
('Cafe DAX', 'Little Italy', '267 Rue Saint-Zotique Ouest');
