INSERT INTO vendors(vendor_name, city_name)
VALUES
('Dispatch', 'Little Italy'),
('Cafe Pista', 'Rosemont'),
('Cafe Dei Campi', 'Rosemont'),
('Cafe L/Etincelle', 'Rosemont'),
('Le Bruloir', 'Ahuntsic'),
('Le Cafe Creme', 'Ahuntsic'),
('Le Cafe Creme', 'Ahuntsic'),
('Cafe Aroma Paninoteca', 'Ahuntsic'),
('Paolino', 'Ahuntsic'),
('Cafe Petit Flore', 'Ahuntsic'),
('Salerno', 'Ahuntsic'),
('Cafe Noir', 'Ahuntsic'),
('Le Bruloir', 'Ahuntsic'),
('Cafe Gentile', 'Ahuntsic'),
('Cafe Vito', 'Villeray'),
('Cafe Vito', 'Villeray'),
('Ferlucci', 'Villeray'),
('Cafe Oui Mais Non', 'Villeray'),
('Cafe Larue et Fils', 'Villeray'),
('Loukouman', 'Villeray'),
('Le Berri Cafe', 'Villeray'),
('Melk', 'NDG'),
('Cafe de Mercanti', 'NDG'),
('Croissant Monkland', 'NDG'),
('Mate', 'NDG'),
('Caravane', 'NDG'),
('Cafe 92', 'NDG'),
('Elementaire Cafe', 'NDG'),
('Cafe Zephyr', 'NDG'),
('Rockaberry', 'NDG'),
('Cafe Larue & Fils', 'Villeray'),
('Cafe Myriade', 'Little Italy'),
('Pikolo Espresso Bar', 'Little Italy'),
('Ferlucci', 'Villeray'),
('Cafe Olimpico', 'Little Italy'),
('Cafe Olimpico', 'Little Italy'),
('Cafe Parvis', 'Little Italy'),
('Tommy', 'Downtown'),
('Picolo Espresso Bar', 'Villeray'),
('Café Névé', 'Rosemont'),
('Cafe Olimpico', 'Little Italy'),
('Paquebot', 'Rosemont'),
('Cafe Odessa', 'Rosemont'),
('La Brume Dans Mes Lunettes', 'Rosemont'),
('Caffe San Simeon', 'Little Italy'),
('Caffe Italia', 'Little Italy'),
('Cafe DAX', 'Little Italy'),
('The Standard', 'Mile End');
